# Generated by Django 5.1.5 on 2025-01-15 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('balance_after_borrowing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userborrowings', to='User.usermodel')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookborrowings', to='Book.bookmodel')),
            ],
            options={
                'ordering': ['borrow_date'],
            },
        ),
    ]
