# Generated by Django 5.1.5 on 2025-01-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
