# Generated by Django 5.1.5 on 2025-01-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Borrow', '0002_alter_borrowmodel_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='balance_after_borrowing',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
