# Generated by Django 5.1.5 on 2025-01-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='Book/media/uploads')),
                ('borrowing_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ManyToManyField(to='Category.categorymodel')),
            ],
        ),
    ]
