# Generated by Django 5.1.5 on 2025-01-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='borrowing_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
